(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 213 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(column-number-mode nil)
 '(css-indent-offset 2)
 '(css-mode-indent-depth 2 t)
 '(default-frame-alist (quote ((font-backend ns) (fontsize . 0) (font . "-apple-Inconsolata-medium-normal-normal-*-16-*-*-*-m-0-iso10646-1") (left-fringe . 4) (right-fringe . 12) (menu-bar-lines . 1) (tool-bar-lines . 0) (modeline . t) (fringe) (vertical-scroll-bars . right) (cursor-type . box) (background-color . "gray4") (background-mode . dark) (border-color . "black") (cursor-color . "Red") (foreground-color . "papaya whip") (mouse-color . "black"))))
 '(fill-column 100)
 '(find-file-existing-other-name nil)
 '(global-linum-mode t)
 '(global-visual-line-mode nil)
 '(grep-find-ignored-files (quote (".#*" "*.rbc" "*.o" "*~" "*.bin" "*.lbin" "*.so" "*.a" "*.ln" "*.blg" "*.bbl" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.pfsl" "*.dfsl" "*.p64fsl" "*.d64fsl" "*.dx64fsl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" "*.pg" "*.tp" "*.vr" "*.cps" "*.fns" "*.kys" "*.pgs" "*.tps" "*.vrs" "*.pyc" "*.pyo" "*.log" "*.sql")))
 '(grep-find-template "find -L . <X> -type f <F> -exec grep <C> -nH -e <R> {} /dev/null \\;")
 '(hippie-expand-try-functions-list (quote (try-expand-all-abbrevs try-expand-dabbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill try-complete-file-name-partially try-complete-file-name try-complete-lisp-symbol-partially try-complete-lisp-symbol)))
 '(javascript-indent-level 2)
 '(js-indent-level 2)
 '(ns-tool-bar-display-mode nil t)
 '(ns-tool-bar-size-mode nil t)
 '(org-agenda-files nil)
 '(rinari-rgrep-file-endings "*.*" t)
 '(ruby-deep-indent-paren nil)
 '(show-paren-mode nil)
 '(standard-indent 2)
 '(tab-width 2)
 '(toolbar-menu-show--copy nil)
 '(toolbar-menu-show--customize t)
 '(toolbar-menu-show--cut nil)
 '(toolbar-menu-show--paste nil)
 '(vc-follow-symlinks t)
 '(visual-line-mode nil t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(autoface-default ((t (:inherit default))))
 '(comint-mode-default ((t (:inherit autoface-default :background "#2f4f4f"))))
 '(completion-list-mode-default ((t (:inherit autoface-default))) t)
 '(dired-mode-default ((t (:inherit autoface-default :background "#3f3f3f"))) t)
 '(echo-area ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 150 :width normal :family "Inconsolata"))))
 '(emacs-lisp-mode-default ((t (:inherit autoface-default))) t)
 '(font-lock-constant-face ((t (:foreground "#ff4500"))))
 '(font-lock-string-face ((t (:foreground "#cdad00"))))
 '(help-mode-default ((t (:inherit autoface-default :background "gray4"))) t)
 '(hl-line ((t (:background "#212121"))))
 '(linum ((t (:background "gray" :foreground "#966"))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) (:background "*"))))
 '(mumamo-background-chunk-submode ((((class color) (min-colors 88) (background dark)) (:background "gray6"))))
 '(nxhtml-mode-default ((t (:inherit nxml-mode-default :background "#0a0a0a"))) t)
 '(ruby-mode-default ((t (:inherit autoface-default :background "gray4" :foreground "gainsboro"))) t)
 '(shell-mode-default ((t (:inherit comint-mode-default :background "dark slate gray" :foreground "papaya whip"))))
 '(sql-interactive-mode-default ((t (:inherit autoface-default :background "#9f5118")))))
